# Generated by Django 3.1 on 2020-08-29 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('app_id', models.IntegerField()),
                ('args', models.TextField()),
                ('core', models.TextField()),
            ],
            options={
                'ordering': ['created'],
            },
        ),
    ]
