# Generated by Django 3.1 on 2020-10-18 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('responses', '0002_response_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='response',
            name='command',
            field=models.TextField(default=''),
        ),
    ]
